---
abstract: 'Helps you track down memory leaks in your code'
author:
  - 'Ben van Staveren <madcat@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-LeakTracker
requires:
  Data::Dumper: 0
  Devel::Cycle: 0
  Devel::Events::Filter::RemoveFields: 0
  Devel::Events::Filter::Stamp: 0
  Devel::Events::Filter::Stringify: 0
  Devel::Events::Generator::Objects: 0
  Devel::Events::Handler::Log::Memory: 0
  Devel::Events::Handler::Multiplex: 0
  Devel::Events::Handler::ObjectTracker: 0
  Devel::Size: 0
  Mojo::Base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/benvanstaveren/Mojolicious-Plugin-LeakTracker/issues
  repository: git://github.com/benvanstaveren/Mojolicious-Plugin-LeakTracker.git
version: 1.00
